version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      react-packages:
        patterns:
          - "react"
          - "react-dom"
      docusaurus-packages:
        patterns:
          - "@docusaurus/*"
      eslint-packages:
        patterns:
          - "eslint"
          - "eslint-*"
          - "@typescript-eslint/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
