version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    versioning-strategy: 'increase'
    groups:
      react-packages:
        patterns:
          - 'react'
          - 'react-dom'
      docusaurus-packages:
        patterns:
          - '@docusaurus/*'
      eslint-packages:
        patterns:
          - 'eslint'
          - 'eslint-*'
          - '@typescript-eslint/*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    versioning-strategy: 'increase'
    schedule:
      interval: 'monthly'
