name: toWebp

on:
  pull_request:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}
    - name: setup webp 
      run: sudo apt-get install webp
    - name: Get add image files and convert
      id: convert
      run: |
        files=$(git diff --name-only origin/${GITHUB_BASE_REF}...origin/${GITHUB_HEAD_REF} --diff-filter=A -- '*.png') # PR内でpngに関して新たに追加されたものを取得
        if [ -n "$files" ]; then
          echo "isConverted=true" >> $GITHUB_OUTPUT
          for file in $files; do
            name="${file%.png}" # 拡張子を削除
            cwebp "$name.png" -o "$name.webp" # png->webp
            rm "$name.png"
          done
        fi
    - name: commit and push
      run: |
        if [ ${{ steps.convert.outputs.isConverted }} ]; then
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "convert to webp" -a
          git push
        fi
